name: Build and publish snapshot version

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: clean build --info --stacktrace

      - name: Upload artifacts to Actions
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs

      - name: Upload artifacts to Maven
        run: echo "TODO"