name: Build and publish snapshot if it works

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Compile the plugin, upload to Actions
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: clean build --info --stacktrace

      - name: Upload artifacts to Actions
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs

  compile_samples:
    name: Compile sample projects
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        sample: [ "1.3.2", "1.4.7", "1.4.7-gradle8", "1.5.2", "1.6.4", "1.7.10" ]
        java_version: [ "8", "17" ]
        include:
          - sample: "1.4.7-gradle4"
            java_version: "8"
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Setup Java ${{matrix.java_version}}
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "${{matrix.java_version}}"

      - name: Build sample ${{matrix.sample}} with Gradle
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: clean build --info --stacktrace -Dvoldeloom.refreshDependencies=true
          build-root-directory: "./sample/${{matrix.sample}}"

  publish:
    name: Publish `-SNAPSHOT` artifact to Sleeping Town maven
    runs-on: ubuntu-latest
    needs: compile_samples
#security is my passion (ideally pull_request actions won't fire this?? reh)
    if: (github.event_name == 'push' && github.ref_name == 'disaster-time')
    environment: publishing
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Publish with Gradle
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: publish --info --stacktrace -Ppublish-username=${{secrets.PUBLISH_USERNAME}} -Ppublish-password=${{secrets.PUBLISH_PASSWORD}}