name: Compile sample projects

on: [push, pull_request, workflow_dispatch]

jobs:
  build_samples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sample: ["1.3.2", "1.4.7", "1.5.2"]
        java_version: ["8", "17"]
        include:
          - java_version: "8"
            sample: "1.4.7-gradle4"
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Setup Java ${{matrix.java_version}}
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "${{matrix.java_version}}"

      - name: Build sample $${matrix.sample}} with Gradle
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: clean build
          build-root-directory: "./sample/${{matrix.sample}}"