name: Publish full release to Maven

on:
  push:
    branches:
      - 'disaster-time'
    tags:
#This isn't a conventional regular expression, it's some weird custom github pattern-match thing
#https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet 
      - 'v[0-9.]*'


jobs:
  publish-full:
    name: Publish ${{github.ref_name}} artifact to Sleeping Town maven
    runs-on: ubuntu-latest
    needs: compile_samples
    environment: publishing
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Publish with Gradle
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: publish --info --stacktrace -DVOLDE_RELEASE_VERSION=${{github.ref_name}} -Pdrypublish-username=${{secrets.PUBLISH_USERNAME}} -Pdrypublish-password=${{secrets.PUBLISH_PASSWORD}}