name: Publish full release to Maven

on:
  release:
    types: [created]

jobs:
  publish-full:
    name: Publish ${{github.ref_name}} artifact to Sleeping Town maven
    runs-on: ubuntu-latest
    environment: publishing
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Publish with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: publish --info --stacktrace -Ppublish-username=${{secrets.PUBLISH_USERNAME}} -Ppublish-password=${{secrets.PUBLISH_PASSWORD}}
        env:
          VOLDE_RELEASE_MODE: 1