name: Publish snapshot to Maven

on:
  push:
    branches: "disaster-time"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: publishing
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Publish with Gradle
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: publish --info --stacktrace -Ppublish-username=${{secrets.PUBLISH_USERNAME}} -Ppublish-password=${{secrets.PUBLISH_PASSWORD}}